### ISSUE TITLE
Push of pipeline logs to Grafana Loki fails

### ISSUE THREAD

**Issue by MoritzWeber0** [DSD-DBS/capella-collab-manager#1180]
Steps to reproduce: 

1. Trigger a pipeline
2. It doesn't show any logs or events

In the backend logs, you can see:

```
time="2023-11-08 08:16:44,525" level=DEBUG name=capellacollab.projects.toolmodels.backups.runs.interface function=_fetch_logs_of_job_runs message="Fetch logs of job 198"
time="2023-11-08 08:16:44,620" level=ERROR name=root function=push_logs_to_loki message="Error pushing logs to Grafana Loki"
Traceback (most recent call last):
  File "/tmp/backend/capellacollab/core/logging/loki.py", line 58, in push_logs_to_loki
    response.raise_for_status()
  File "/opt/.venv/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://loki-gateway.capella-collab-prod.svc.cluster.local/loki/api/v1/push
time="2023-11-08 08:16:44,525" level=INFO name=root function=push_logs_to_loki message="Response from Loki API: loghttp.PushRequest.Streams: []loghttp.LogProtoStream: unmarshalerDecoder: Value is string, but can't find closing '"' symbol, error found in #10 byte of ...|fpga\""]]}]}|..., bigger context ...|"Started container xeiktqlakymkeccjkcyozfpga\""]]}]}|...
```

**Comment by MoritzWeber0** [comment]
> This issue seems to be related to or caused by [grafana/loki#10738](https://github.com/grafana/loki/issues/10738). So the underlying problem is that they have started to enforce that labels must be strings and in our case we also have numbers as labels. However, as far as I can see, this change is being reverted, so we can either wait for a new loki version or try to see if converting our labels to strings would resolve the issue. What's your opinion on this, @MoritzWeber0?

Even though they state that they added a test case for it, it looks like they expect strings - let's transform all labels to strings before pushing.
