### ISSUE TITLE
Got an error while try to see git model source in settings

### ISSUE THREAD

**Issue by formorter** [DSD-DBS/capella-collab-manager#1580]
Hi there
I have latest version of capella-collab-manager(3.2.4)
When im try to open git model settings, i got white screen and error log in console
![image](https://github.com/DSD-DBS/capella-collab-manager/assets/72940774/ec1f2153-dd09-4b99-a60a-900f0790d43d)
![image](https://github.com/DSD-DBS/capella-collab-manager/assets/72940774/d083a1a9-b38b-4780-be15-04a1ac61daf0)
Error in console:
```
ERROR NullInjectorError: R3InjectorError(Standalone[Uf])[Ln -> Ln -> Ln]: 
  NullInjectorError: No provider for Ln!
    at tR.get (main-G2S4ARLW.js:15:1139)
    at oC.get (main-G2S4ARLW.js:15:10767)
    at oC.get (main-G2S4ARLW.js:15:10767)
    at oC.get (main-G2S4ARLW.js:15:10767)
    at TB.get (main-G2S4ARLW.js:15:62398)
    at wX (main-G2S4ARLW.js:15:22356)
    at xX (main-G2S4ARLW.js:15:22597)
    at v (main-G2S4ARLW.js:15:44114)
    at Uf.ɵfac [as factory] (main-G2S4ARLW.js:261:76448)
    at bg (main-G2S4ARLW.js:15:23803)
```
If you can, please, help me fix it

**Comment by MoritzWeber0** [comment]
Hi, sorry for the late reply. I can reproduce it and will provide a fix today.

**Comment by MoritzWeber0** [comment]
Please try again with [v3.2.5](https://github.com/DSD-DBS/capella-collab-manager/releases/tag/v3.2.5).

**Comment by formorter** [comment]
it works, thanks!
