### ISSUE TITLE
Pipeline triggering seems to fail sometimes

### ISSUE THREAD

**Issue by MoritzWeber0** [DSD-DBS/capella-collab-manager#1913]
```py
time="2024-10-17T14:18:57+0000" level=ERROR name=capellacollab.projects.toolmodels.backups.runs.interface function=_refresh_and_trigger_pipeline_jobs message="Failed fetching logs of jobs"
Traceback (most recent call last):
File "/tmp/backend/capellacollab/projects/toolmodels/backups/runs/interface.py", line 293, in _refresh_and_trigger_pipeline_jobs
_fetch_logs_of_job_runs(run)
File "/tmp/backend/capellacollab/projects/toolmodels/backups/runs/interface.py", line 171, in _fetch_logs_of_job_runs
log_entries = [
^
File "/tmp/backend/capellacollab/projects/toolmodels/backups/runs/interface.py", line 172, in <listcomp>
_transform_kubernetes_logline_to_loki_entry(log_line)
File "/tmp/backend/capellacollab/projects/toolmodels/backups/runs/interface.py", line 99, in _transform_kubernetes_logline_to_loki_entry
timestamp=datetime.datetime.fromisoformat(line.split()[0]),
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Invalid isoformat string: 'Updating'
```

**Comment by MoritzWeber0** [comment]
Also related: 

```py
time="2024-10-17T14:15:26+0000" level=ERROR name=capellacollab.sessions.operators.k8s function=get_job_logs message="Failed fetching logs from Kubernetes"
Traceback (most recent call last):
  File "/tmp/backend/capellacollab/sessions/operators/k8s.py", line 249, in get_job_logs
    if pod_log := self.v1_core.read_namespaced_pod_log(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/.venv/lib/python3.11/site-packages/kubernetes/client/api/core_v1_api.py", line 23957, in read_namespaced_pod_log
    return self.read_namespaced_pod_log_with_http_info(name, namespace, **kwargs)  # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/.venv/lib/python3.11/site-packages/kubernetes/client/api/core_v1_api.py", line 24076, in read_namespaced_pod_log_with_http_info
    return self.api_client.call_api(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/.venv/lib/python3.11/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/.venv/lib/python3.11/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
                    ^^^^^^^^^^^^^
  File "/opt/.venv/lib/python3.11/site-packages/kubernetes/client/api_client.py", line 373, in request
    return self.rest_client.GET(url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/.venv/lib/python3.11/site-packages/kubernetes/client/rest.py", line 244, in GET
    return self.request("GET", url,
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/.venv/lib/python3.11/site-packages/kubernetes/client/rest.py", line 238, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Audit-Id': '2f1390a1-d321-445b-89fa-ad3f0279af6f', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload', 'Date': 'Thu, 17 Oct 2024 14:15:26 GMT', 'Content-Length': '264'})
HTTP response body: {
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "container \"hvadeqtpndfawevuenvvlzamb\" in pod \"hvadeqtpndfawevuenvvlzamb-d2msv\" is waiting to start: ContainerCreating",
  "reason": "BadRequest",
  "code": 400
}
```

The best option would be to attach an promtail container to the Job instead of collecting the logs from the CCM. Or alternatively use a proper job scheduling like Celery.
