### ISSUE TITLE
Stability issues on local deplyoment

### ISSUE THREAD

**Issue by vik378** [DSD-DBS/capella-collab-manager#800]
Here are a few observations:
- Prometheus and grafana are unreacheable even though I can start a Capella session
- after some time prometheus becomes available but restarts itself time to time
- Guacamole goes slow and dies at the end

Some more evidence below:
![image](https://github.com/DSD-DBS/capella-collab-manager/assets/8280844/b78f6685-5d72-4f41-9663-f34f6eac0f0d)

some time later we get this:
```
dev-prometheus-server-66997ddcd5-5vzmv    0/1     OOMKilled   24 (19s ago)    14d
```

After being kicked out of session (session froze with Connection to Guacamole server is unstable) all attempts to reconnect to the session fail with error and I see this in the backend logs:

```
ime="2023-06-26 18:16:57,942" level=ERROR function=dispatch client="10.42.0.121:58764" trace_id="8B15VI4ZWK" method="POST" path="/api/v1/sessions/ltjzbesbarxwieehakyuyqycg/guacamole-tokens" user="admin" message="HTTPConnectionPool(host='dev-guacamole-guacamole', port=8080): Read timed out. (read timeout=2)"
Traceback (most recent call last):
  File "/tmp/backend/capellacollab/core/logging/__init__.py", line 75, in dispatch
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/backend/capellacollab/core/logging/__init__.py", line 86, in dispatch
    response: fastapi.Response = await call_next(request)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/starlette_prometheus/middleware.py", line 57, in dispatch
    raise e from None
  File "/usr/local/lib/python3.11/site-packages/starlette_prometheus/middleware.py", line 53, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 241, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 169, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/backend/capellacollab/sessions/routes.py", line 602, in create_guacamole_token
    token = guacamole.get_token(
            ^^^^^^^^^^^^^^^^^^^^
  File "/tmp/backend/capellacollab/sessions/guacamole.py", line 53, in get_token
    r = requests.post(
        ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
```

There is more about Prometheus:

```
dev-prometheus-server-66997ddcd5-5vzmv    0/1     CrashLoopBackOff   26 (20s ago)    14d

```

although Prometheus logs look quite clean:

```
ts=2023-06-26T18:20:18.629Z caller=head.go:755 level=info component=tsdb msg="WAL segment loaded" segment=36 maxSegment=37
ts=2023-06-26T18:20:18.631Z caller=head.go:755 level=info component=tsdb msg="WAL segment loaded" segment=37 maxSegment=37
ts=2023-06-26T18:20:18.727Z caller=head.go:792 level=info component=tsdb msg="WAL replay completed" checkpoint_replay_duration=3.194694137s wal_replay_duration=896.982229ms wbl_replay_duration=407ns total_replay_duration=4.092511464s
ts=2023-06-26T18:20:18.732Z caller=main.go:1040 level=info fs_type=EXT4_SUPER_MAGIC
ts=2023-06-26T18:20:18.732Z caller=main.go:1043 level=info msg="TSDB started"
ts=2023-06-26T18:20:18.732Z caller=main.go:1224 level=info msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
ts=2023-06-26T18:20:18.734Z caller=kubernetes.go:327 level=info component="discovery manager scrape" discovery=kubernetes config=kubernetes-services msg="Using pod service account via in-cluster config"
ts=2023-06-26T18:20:18.828Z caller=main.go:1261 level=info msg="Completed loading of configuration file" filename=/etc/prometheus/prometheus.yml totalDuration=95.821163ms db_storage=2.526µs remote_storage=3.935µs web_handler=1.151µs query_engine=2.113µs scrape=604.008µs scrape_sd=93.334728ms notify=2.49µs notify_sd=4.826µs rules=828.688µs tracing=10.91µs
ts=2023-06-26T18:20:18.828Z caller=main.go:1004 level=info msg="Server is ready to receive web requests."
ts=2023-06-26T18:20:18.828Z caller=manager.go:995 level=info component="rule manager" msg="Starting rule manager..."
ts=2023-06-26T18:20:25.936Z caller=compact.go:514 level=info component=tsdb msg="write block resulted in empty block" mint=1687356000000 maxt=1687363200000 duration=433.406659ms
ts=2023-06-26T18:20:26.028Z caller=head.go:1293 level=info component=tsdb msg="Head GC completed" caller=truncateMemory duration=91.651645ms
ts=2023-06-26T18:20:26.028Z caller=checkpoint.go:100 level=info component=tsdb msg="Creating checkpoint" from_segment=34 to_segment=35 mint=1687363200000
ts=2023-06-26T18:20:26.738Z caller=head.go:1261 level=info component=tsdb msg="WAL checkpoint complete" first=34 last=35 duration=709.892759ms
viktor@
```

Prometheus and Grafana both look quite clean from the logs perspective and both are unreachable (although I managed to see prometheus page 1 time, I couldnt make any query and it was gone almost instant into 403).

attempts to restart session failed. until guacamole pod finally got restarted:

```
dev-guacamole-guacamole-c4b788547-kgql9   2/2     Running   20 (117s ago)    14d
```

last words from the session:
![image](https://github.com/DSD-DBS/capella-collab-manager/assets/8280844/973cb791-98cb-4622-8541-63792fa67fd7)

**Comment by amolenaar** [comment]
How did you set up / start collab manager? Which version are you using (main?)?

**Comment by vik378** [comment]
collab-manager is the latest main, started via make deploy as per README.md
